[[regexes]]
pattern = '(?<text>PS-\d+)'
replacement = "https://www.jira.com/$text"
limit = 1

[[regexes]]
pattern = '(?<text>GTPR-\d+)'
replacement = "http://www.grtp.de/issue/$text"
limit = 0
code = true
