[[replacements]]
type = "Regex"
pattern = 'PS-(?<s>\d+)'
replacement = "https://www.jira.com/PS-$s"
limit = 1

[[replacements]]

type = "Regex"
pattern = '(?<p>GTPR-\d+)'
replacement = "http://www.grtp.de/issue/$p"
limit = 0
