[[regex]]
tag = 'PS-'
tail = '\d+'
replacement = "https://internal.jira.com/$text"
limit = 1
strip_tag = false

[[regex]]
tag = 'GTPR-'
tail = '\d+'
replacement = "http://www.grtp.de/issue/$text"
limit = 0
code = true
strip_tag = false
