[[regex]]
tag = 'PS-'
tail = '\d+'
replacement = "https://internal.jira.com/$text"
limit = 1
tail_only = false

[[regex]]
tag = 'GTPR-'
tail = '\d+'
replacement = "http://www.grtp.de/issue/$text"
limit = 0
code = true
tail_only = false

[[regex]]
tag = 'keyword:'
tail = '\w+'
replacement = 'https://doc.rust-lang.org/std/keyword.$text.html'
limit = 1
code = true
tail_only = true
replace_text = true
