[package]
name = "snippet"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
relative-path = { version = "1.9.0", features = ["serde"] }
serde = { version = "1.0.188", features = ["derive"] }
