[package]
name = "markdown-normalizer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.72"
clap = { version = "4.3.16", features = ["derive"] }
pulldown-cmark = "0.9.3"
pulldown-cmark-to-cmark = "11.0.0"
