[package]
name = "snippet-extractor"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
assert_cmd = "2.0.12"
assert_fs = "1.0.13"

[dependencies]
anyhow = "1.0.72"
clap = { version = "4.3.16", features = ["derive"] }
pest = "2.7.1"
pest_derive = "2.7.1"
serde = "1.0.171"
serde_json = "1.0.103"
snippet = { path = "../snippet" }
walkdir = "2.3.3"
