[package]
name = "snippet-extractor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.3.11", features = ["derive"] }
pest = "2.7.0"
pest_derive = "2.7.0"
serde = "1.0.170"
serde_json = "1.0.100"
snippet = { path = "../snippet" }
walkdir = "2.3.3"
